#!/usr/bin/env python3
"""Build a clickable world map from Natural Earth public-domain geometry.

Source: https://github.com/nvkelso/natural-earth-vector (public domain)
File: geojson/ne_50m_admin_0_countries.geojson

The committed SVG and country list are generated by this script. Re-run it
when the geometry source changes. The script reads WORLD_GEOJSON when set,
otherwise it expects the file at the path passed as argv[1].
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import escape

WIDTH = 960
HEIGHT = 480
MIN_DIST = 1.6

ROOT = Path(__file__).resolve().parents[1]
SVG_OUT = ROOT / "components" / "ui" / "public" / "world.svg"
JSON_OUT = ROOT / "components" / "ui" / "src" / "data" / "countries.json"


def project(lon: float, lat: float) -> tuple[float, float]:
    x = (lon + 180.0) / 360.0 * WIDTH
    y = (90.0 - lat) / 180.0 * HEIGHT
    return x, y


def simplify(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    if not points:
        return []
    kept = [points[0]]
    limit = MIN_DIST * MIN_DIST
    for point in points[1:]:
        dx = point[0] - kept[-1][0]
        dy = point[1] - kept[-1][1]
        if dx * dx + dy * dy >= limit:
            kept.append(point)
    if kept[-1] != points[-1]:
        kept.append(points[-1])
    return kept


def ring_path(ring: list[list[float]]) -> str | None:
    projected = [project(float(lon), float(lat)) for lon, lat in ring]
    points = simplify(projected)
    if len(points) < 3:
        return None
    commands = [f"M{points[0][0]:.1f},{points[0][1]:.1f}"]
    commands.extend(f"L{x:.1f},{y:.1f}" for x, y in points[1:])
    commands.append("Z")
    return "".join(commands)


def iter_rings(geometry: dict) -> list[list[list[float]]]:
    kind = geometry["type"]
    coords = geometry["coordinates"]
    if kind == "Polygon":
        return list(coords)
    if kind == "MultiPolygon":
        return [ring for polygon in coords for ring in polygon]
    return []


def iso_code(props: dict) -> str | None:
    primary = props.get("ISO_A2") or ""
    if len(primary) == 2 and primary != "-99":
        return primary
    fallback = props.get("ISO_A2_EH") or ""
    if len(fallback) == 2 and fallback != "-99":
        return fallback
    return None


def centroid(ring: list[list[float]]) -> tuple[float, float]:
    lon = sum(point[0] for point in ring) / len(ring)
    lat = sum(point[1] for point in ring) / len(ring)
    return project(lon, lat)


def main() -> None:
    source = Path(os.environ.get("WORLD_GEOJSON") or sys.argv[1])
    payload = json.loads(source.read_text())
    grouped: dict[str, dict] = {}
    for feature in payload["features"]:
        props = feature["properties"]
        code = iso_code(props)
        if code is None:
            continue
        name = props.get("NAME_EN") or props.get("ADMIN") or code
        entry = grouped.setdefault(code, {"code": code, "name": name, "paths": [], "dots": []})
        rings = iter_rings(feature["geometry"])
        wrote = False
        for ring in rings:
            if len(ring) < 3:
                continue
            path = ring_path(ring)
            if path:
                entry["paths"].append(path)
                wrote = True
        if not wrote and rings:
            entry["dots"].append(centroid(rings[0]))

    countries = sorted(
        ({"code": code, "name": entry["name"]} for code, entry in grouped.items()),
        key=lambda item: item["name"],
    )
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    SVG_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(countries, indent=2) + "\n")

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-label="World map">',
        "  <title>World map</title>",
        "  <rect width=\"100%\" height=\"100%\" class=\"ocean\" />",
    ]
    for code in sorted(grouped):
        entry = grouped[code]
        lines.append(
            f'  <g class="country" data-iso="{escape(code)}" data-name="{escape(entry["name"])}">'
        )
        for path in entry["paths"]:
            lines.append(f'    <path d="{path}" />')
        for x, y in entry["dots"]:
            lines.append(f'    <circle cx="{x:.1f}" cy="{y:.1f}" r="3" />')
        lines.append("  </g>")
    lines.append("</svg>")
    SVG_OUT.write_text("\n".join(lines) + "\n")
    print(f"countries {len(countries)} svg_bytes {SVG_OUT.stat().st_size}")


if __name__ == "__main__":
    main()
